year: 2026
contact_email: info@redteamsummit.com
event_date: March 10-11, 2026
cfp_close_date: January 07, 2026
cfp_url: https://cfp.redteamsummit.com/red-team-summit-2026/cfp
show_cfp: true
logo_path:
location: McLean, Virginia
show_map: false
